import 'dart:math';

class Quotes {
  final _random = new Random();
  int random = 1;
  List<String> quote = [
    "Water: The liquid that sustains life, Conserve it!",
    "Saving water is a good deed, it’s an essential resource, we all need!",
    "If not now? then when? Save water before you see it end.",
    "If we care for Water Now, It will care for us in the Present and Future.",
    "Don’t let me spot you wasting water!",
    "Don’t forget to save water. I’m watching you!",
    "The choice is yours- Save it or Waste it.",
    "Water preservation to prevent future devastation.",
    "Before it all wastes away, let’s start conserving water today!",
    "Save Water. It’s not just a drop in the bucket. It’s a Life",
    "Save water Every day, keep scarcity Always away.",
    "Life on earth would not exist without liquid water.",
    "The bright future begins with clean water.",
    "Water is precious but its availability is serious.",
    "If you Don’t want mental hydration then Think about water conservation.",
    "The less you use, the more you save.",
    "Don’t waste water, so we can have it another day.",
    "Don’t drop out to save the drop.",
    "A drop of water is worth more than a sack of gold to a thirsty man.",
    "Store water for Dry days!",
    "Save water; it will save you later.",
    "When you conserve water, you conserve life!",
    "Life depends on water, the reservoir depends on you.",
    "Save water every day and keep disaster away.",
    "Water pollution is a bad solution.",
    "No water pollution is the only solution.",
    "Want life or death, you choose! Stop water pollution!",
    "Clean water is a blessing from God, don’t pollute it.",
    "Say no to water pollution and lead a healthy life.",
    "Water is to drink not pollute and waste",
    "Say no to water pollution!",
    "Love water, Hate pollution",
    "Protect Your Water Bodies From Pollution.",
    "Water: The original NO calorie drink.",
    "There are a number of ways to save water. And, they all start with you.",
    "Always remember to fill the glass up to the need.",
    "More water, more happiness.",
    "Put a stop to the drop.",
    "A Drip can Destroy many Drops.",
    "Please Think and don’t Waste Water in the Sink.",
    "Don’t let the water run when you brush your teeth.",
    "Turn off the faucet while brushing your teeth.",
    "Save Some Water for mankind, Close the tap, don’t be blind.",
    "Close the water tap after use always.",
    "It’s no fun to let the water run.",
    "Save water flush less.",
    "It’s all about water!",
    "There is a thin line between using water and wasting water.",
    "How many drops make up an ocean? Conserve water; every drop counts.",
    "Imagine a day without water",
    "Waste water today – Live in desert tomorrow.",
    "Walk in the desert, you will realize the cost of Water.",
    "Go to a desert to know the importance of water",
    "We never know the worth of water till the well is dry. Save Water!!",
    "Waterless planets have no life.",
    "What if you stopped drinking water?",
    "Never throw drinking water; always save to have it later.",
    "Start water conservation to prevent future dehydration.",
    "Save water! Your small step can be a major change.",
    "Be the real human being and save the water from your end.",
    "If you don’t know, ask the importance of water to a thirsty man.",
    "Teach your kids to respect water so that they can have it later.",
    "Rainwater tank, won’t break the bank.",
    "A Gallon Saved is a Gallon Earned",
    "The wars of the twenty-first century will be fought over water.",
    "The water you pollute will find its way back to you.",
    "Don’t flush our planet’s most valuable resource.",
    "Conserve water, every drop counts!",
    "Save water today, use it tomorrow",
    "Destroy water, you destroy life.",
    "Don’t make nature cry, keep your water clean.",
    "Water is the most critical resource issue of our lifetime and our children’s lifetime.",
    "Even a drop can bring life! Save water!",
    "The best gift you can give to the coming generation is water.",
    "Saving water is in our hands.",
    "The habit of saving water is the best habit",
    "Save water, it’s our most valuable resource",
    "Save water, do your part",
    "Save water for your bright future",
    "Save water, the world depends on it",
    "Saving water can save the world",
    "No Water – No Life",
    "Conserve water, conserve life.",
    "Water is the substance of life. Treasure it!",
    "Water is not the source of life, it is life.",
    "If Water is Life, then why we are wasting it?",
    "We forget that the water cycle and the life cycle are one.",
    "Water is a human right!",
    "Water, the beauty of nature",
    "Think Blue and go Green!",
    "It takes a lot of blue to stay green.",
    "WATER, the DNA of life",
    "Water = Life, Conservation = Future!",
    "There are no substitutes for water.",
    "Water, a wonder liquid",
    "Water is sacred. Kindly save it.",
    "Water for the future generations Priceless.",
    "Water, water everywhere but not a drop to drink.",
    "One drop could save our thirsty world! Conserve Water!",
    "Water is the one substance from which the earth can conceal nothing, it sucks out its innermost secrets and brings them to our very lips.",
    "Think of water conservation to prevent it from extinction.",
    "Use water only when you need, like costly things.",
    "Water is to save, otherwise, you will crave."
  ];
  String get randomquote {
    return quote[random];
  }

  void randomindex() {
    random = _random.nextInt(103);
  }
}
